debug: false
display_error: false

config:
    database:
        db.options:
            dbname:
            user:
            password:
            host: localhost
            driver: pdo_mysql
            charset: utf8
            port: 3306